### ISSUE TITLE
Blog: Large images overflow horizontally

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#788] opened 2023-03-07 00:59 UTC
### What happened?

> [4:54 PM]Commodore Jellyfish: my new blog has image overflow for the first image

<img width="210" alt="image" src="https://user-images.githubusercontent.com/31261035/223291362-40b2be88-0736-4599-8e80-ebcfca7dd58f.png">

Large images are expected to scale down to fit the width of the client's screen.

Thank you @stephaniePocci for the bug report!

**Comment by stephaniePocci** [comment] 2023-03-07 01:13
Duplicate of #789

**Closed as not planned by stephaniePocci** 2023-03-07 01:13 UTC
Labels: bug, squirtle
