### ISSUE TITLE
Happy Pokemon Day Banner 👀

### ISSUE THREAD

**Issue by caretcakejake** [acmcsufoss/acmcsuf.com#783] opened 2023-02-25 01:24 UTC
### What's your idea?

Funny idea to have a banner that says "Happy Pokemon Day!" Timed research issue given that 02/27 is Pokemon day.
@EthanThatOneKid.

**Comment by EthanThatOneKid** [comment] 2023-04-02 19:32
Closing as duplicate of #181.

**Closed as not planned by EthanThatOneKid** 2023-04-02 19:32 UTC
Labels: enhancement
